### ISSUE TITLE
dataset AA000015 reports corrupted data

### ISSUE THREAD

**Issue by kusala9** [kusala9/S-58#3]
Could you have a look at this dataset, when I convert it to ASCII it reports ‘corrupted data’ for records 0001 5 and 0001 6

After this it appears to covert the remaining geo records correctly, however when it gets to the feature records ( 0001 117 onwards) it is does not convert the FOIDS correctly

**Comment by kusala9** [comment]
my brain dump...

ok, the issue is test 24..... depends how you define "not reference a SG3D field" really. I think you need something that is 8211 consistent (i.e the DDR is consistent with the data... then you can trap this error. 

Maybe we make an SG3D with only X,Y values in the DDR and a sounding that points to a valid SG2D - that would do it.

**Comment by kusala9** [comment]
problem is that record 12 points to a 3 byte SG2D and record 13 points to a 2 byte SG3D... Not sure this is what's required.

I think we need to link the SOUNDG to an isolated node (i.e. a genuine SG2D). Optionally we also redefine SG3D as 2b24 (2 bytes). That buggers up ALL the bathy in the cell but it's worth a shot....

**Comment by kusala9** [comment]
There are two records causing problems here. Record VRID=12 and VRID=13. Record 12 has an SG2D which is actually an SG3D and Record 13 has the opposite (i.e. an SG3D which should be an SG2D). 

I just created branch JP_Test_15 - this contains a .000 with a replacement for VRID=12 where the SG3D is actually an SG2D (in the catalogue and data as well). I shortened the record and remade all the catalogue entries in the record header. So, any SOUNDG feature that used to point to the SG3D in Record 12 now will find an SG2D (which is non-corrupt). I also fixed Record 13 - we need to work out if we should do the other test case???

**Comment by Richard-Fowle** [comment]
I've looked at the test data, its now correctly triggering the required checks, but also additionally check 555 'Incorrect data order'. 

![image](https://user-images.githubusercontent.com/48444903/55059702-ec720c80-506f-11e9-945d-a754dfeb8ce9.png)

Is it possible to re-order the records so that the two invalid records are after the last SG3D record (VI - 14)

**Comment by kusala9** [comment]
ok - I reordered the records... 0001 records also re-ordered...

**Comment by Richard-Fowle** [comment]
Ordering good, however check 540a is now not being triggered, also there is a mistake in the header causing error 27 the highlighted B13 should be B12 ........ 

![image](https://user-images.githubusercontent.com/48444903/55081278-d5e3a980-509f-11e9-8b65-8450034eb616.png)

If you can set one of the subfields to Null, I think setting the FSPT.NAME subfield of the very last recod to NULL should do the trick .....

![image](https://user-images.githubusercontent.com/48444903/55082108-59ea6100-50a1-11e9-9879-c040e30ea24d.png)

**Comment by kusala9** [comment]
what's check 540a?

**Comment by Richard-Fowle** [comment]
[cid:image001.png@01D4E4AF.732CE9C0]

Med venlig hilsen


Richard Anthony Fowle
Overkartograf

D. +45 7254 5179
E. riafo@gst.dk


[Energi-, Forsynings- og Klimaministeriet]

Geodatastyrelsen

Lindholm Brygge 31
9400 Nørresundby

T. +45 7254 5000
W. www.gst.dk

Geodatastyrelsen behandler dine personoplysninger.
Læs mere her<https://gst.dk/om-os/geodatastyrelsens-cookie-og-privatlivspolitik/oplysninger-om-geodatastyrelsens-behandling-af-dine-personoplysninger/>:

**Comment by Richard-Fowle** [comment]
![image](https://user-images.githubusercontent.com/48444903/55084240-2f020c00-50a5-11e9-996b-605e9a86b7b8.png)

**Comment by kusala9** [comment]
ok - I've changed the b13 to b12 (which is correct) - I'm still worried this is knocking over another test (like 8211 fields not being correct but it's easy if we want to change it back.

I remember 540a now - it's difficult. You can't use NAME because you can't make it null - it's fixed width so you can't set it to zero length and 255 is only null for single byte fields. 

I've made a change on the branch to GRUP to 255 which could be construed as NULL I think but need to check. Other suggestions welcome :-) Another one would be where null is defined in the AppB1 table and you use it out of context.....

**Comment by kusala9** [comment]
ah..... "FSPT] field. If the value in the Usage Indicator [USAG] subfield is set to {3} (exterior boundary truncated by the data limit), the MASK subfield must be set to {255} (null), in all other cases it must set to {2}."

So, if we set a MASK=null where USAG =2, say that would constitute an illegal use of Null values...

**Comment by kusala9** [comment]
```
<RECORD>
    <FRID>
        <RCNM>100</RCNM>
        <RCID>42</RCID>
        <PRIM>3</PRIM>
        <GRUP>1</GRUP>
        <OBJL>42</OBJL>
        <RVER>1</RVER>
        <RUIN>1</RUIN>
    </FRID>
    <FOID>
        <AGEN>1810</AGEN>
        <FIDN>562</FIDN>
        <FIDS>1</FIDS>
    </FOID>
    <ATTF>
        <ATTL>87</ATTL>
        <ATVL>20</ATVL>
        <ATTL>88</ATTL>
        <ATVL>30</ATVL>
    </ATTF>
    <FSPT>
        <NAME>8214000000<NAME>
        <ORNT>2</ORNT>
        <USAG>1</USAG>
        <MASK>255</MASK>
        <NAME>8238000000<NAME>
        <ORNT>2</ORNT>
        <USAG>3</USAG>
        <MASK>255</MASK>
```

**Comment by kusala9** [comment]
ok - Record 42, changed first MASK to 255 (null) tho the USAG=1..... should be illeegal.

**Comment by Richard-Fowle** [comment]
all checks triggered (except 540a, but I think the software i am using is wrong and that it should be triggered)
I've uploaded and committed the new version AA400015.000 new ASCII conversion and accompanying documentation
